$kind: http-request
description: >-
  This is a GET request and it is used to "get" data from an endpoint. There is
  no request body for a GET request, but you can use query parameters to help
  specify the resource you want data on (e.g., in this request, we have `id=1`).


  A successful GET response will have a `200 OK` status, and should include some
  kind of response body - for example, HTML web content or JSON data.
url: "{{base_url}}/status"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
      });
    language: text/javascript
order: 1000
