$kind: http-request
url: "{{base_url}}/status"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
      });
    language: text/javascript
order: 1000
